### ISSUE TITLE
why BankAccount linking to client

### ISSUE THREAD

**Issue by nikhilkuyya** [mokuappio/serverless-invoices#12]
just trying to understand what is the context for the bank account linked to client.
which bank account of client is needed in invoice.

i am thinking may be company/team account needed in invoice.
my understanding is company is invoice created by him for the work to the client.
so company share there bank information of his to transact for the work.

**Comment by henritoivar** [comment]
Hi. The idea is that you might want to show different bank details on the invoice depending on who the client is. For example for US based clients you might want to show US bank details, for EU clients you might want to show IBAN details etc.

Hope this makes it a bit more clear.
