### ISSUE TITLE
`npm install` fails on fresh clone

### ISSUE THREAD

**Issue by fallaciousreasoning** [mokuappio/serverless-invoices#14]
When I run npm install after a fresh clone, the install fails. Seems to be something to do with compiling `node-sass`.

`npm --version`: 8.5.5
`node --version`: v16.15.0

`npm install`: [log.txt](https://github.com/mokuappio/serverless-invoices/files/8775239/log.txt)

I had a play around upgrading `node-sass` but it broke a few peer dependencies. I'm pretty unfamiliar with the Vue ecosystem so got out of my depth quite quickly sorry.

**Comment by KarelVendla** [comment]
https://github.com/mokuappio/serverless-invoices/commit/aee38c91c33df29dcbd2be66e89f986565151989
I upgraded node-sass & sass-loader.

Should work now.

Let me know how it goes.

**Comment by fallaciousreasoning** [comment]
It works! Thanks for that, and thanks for this great piece of software!
