### ISSUE TITLE
Misses footer text

### ISSUE THREAD

**Issue by almereyda** [mokuappio/serverless-invoices#16]
This application is one of the finest local invoice generators for browsers.

Yet it misses an important feature, at least for the German market:

- As an invoice creator, I need to add a footer message to the invoice, in order to present my organisation's registration and tax numbers.

Everything else is here, but these details don't need to come within the notes field, why another (multi-line?) field (inbetween the bank account details and the contact information?) is suggested.

See https://invoice-generator.com/ for an example.

**Comment by KarelVendla** [comment]
Hi.
You could create a pull request, otherwise I'll try to take a look in the near future.

**Comment by mareksmakosz** [comment]
@almereyda Thank you for your input. You can add custom fields to your company by clicking on the edit icon next to your company name, top right corner of the invoice.
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2536291/180791146-ff9f9511-29a4-4e9d-9626-5bd6f7bd2d9b.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/2536291/180791001-e06d4dbf-80a7-442e-b1bd-860aa74f39cc.png">

Does that solve your issue?
