### ISSUE TITLE
Customized CSS doesn't carry over into downloaded invoices

### ISSUE THREAD

**Issue by OfGraceAndGlory** [mokuappio/serverless-invoices#20]
I am using the "installed version" of the Moku app. I am not sure if this is where I should post this issue. I made a tweak to the CSS through the customize option on an invoice, but it doesn't show up when I download the PDF.

I am adding/overriding:
`.col-8 {
    flex: 0 0 50%;
    max-width: 50%;
}

.col-4 {
    flex: 0 0 50%;
    max-width: 50%;
}`
because my email and website are long enough that it wont right justify and it looks very sloppy.

This is the output:
![mokuIssues](https://github.com/mokuappio/serverless-invoices/assets/93265678/f00fc41f-d294-4bc5-a6e0-6e747795ca0c)

Interestingly, the serverless online version displays the contact information at the bottom correctly until I download the PDF. But the CSS customization DOES show up in the PDF from there.
Outside of this, I am loving the app. It does exactly what I need.

**Comment by KarelVendla** [comment]
Hi, sorry for the long wait.

I changed the invoice footer's layout to accommodate for longer inputs.
Here's the commit 6126b9e1a0092d75d6e6908852e66d42a02099bf

Hopefully this fixes your problem. 
Please do let me know if you have any more questions or problems!
