### ISSUE TITLE
Label customization

### ISSUE THREAD

**Issue by Stefannag** [mokuappio/serverless-invoices#23]
Hi,

There is in plan to add a label customization? For example, to modify "Invoice", "Item", "Quantity", "Unit", "Price", "Issued at", "Due at", "Date", and so on. 

Maybe it is possible to have a JSON for each language, and a default template so each one could edit that JSON in order to have it in their language, or to have the possibility to add multiple JSONs in order to switch fast between languages. 

Thanks! :)

**Comment by henritoivar** [comment]
You can absolutely already do that by editing the translation files: https://github.com/mokuappio/serverless-invoices/tree/main/public/locales
