### ISSUE TITLE
How to add Tax withheld ?

### ISSUE THREAD

**Issue by bdloner** [mokuappio/serverless-invoices#5]
<img width="386" alt="Screen Shot 2564-06-08 at 20 06 36" src="https://user-images.githubusercontent.com/15920037/121190233-0a189e80-c895-11eb-8e50-5b13907580b0.png">

**Comment by mareksmakosz** [comment]
Hey @bdloner, 
1. Click edit icon next to your company's name
![image](https://user-images.githubusercontent.com/2536291/121199525-adf55080-c87b-11eb-878e-797e7dfe2201.png)

2. Under "Taxes" tab click "+ Tax" button to add a field
![image](https://user-images.githubusercontent.com/2536291/121199893-f90f6380-c87b-11eb-9a34-559df5d429c3.png)

3. Edit the label and tax value and click "Done"
![image](https://user-images.githubusercontent.com/2536291/121199788-e2690c80-c87b-11eb-9624-9875da1880c7.png)

3a. In case you already had some rows inserted, you'll be prompted whether to apply new tax for these rows as well
![image](https://user-images.githubusercontent.com/2536291/121200261-44297680-c87c-11eb-96fb-671f1f82696b.png)


FYI, we just shipped few improvements to the UI in 1e986cd7a09867d1f3530abb6aae9bb7d7d4007c and 11e995a97a82e5d8c8ec313a40ef095bd150106d 
Hope that helps.
