### ISSUE TITLE
I need to updates file upload field as a signature

### ISSUE THREAD

**Issue by sandeepsoni2291** [mokuappio/serverless-invoices#8]
I need to updates file upload field as a signature but file_upload logo stop working its seems like clashing please help ,me out I need to update invoice with signature file add on same invoice detail page but getting error 

![invoice](https://user-images.githubusercontent.com/12181115/130407373-cc3e6cec-bdb0-4aa8-ba3e-4023a626b9e4.PNG)

**Comment by KarelVendla** [comment]
We're happy to help, but first you'd have to share your code with us so we could take a look.

**Comment by KarelVendla** [comment]
Closing for now.
Tagged as enhancement as signature file uploading seems like a valid thing to add.
